spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruiji?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    # 地址
    host: 192.168.50.170
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s

mybatis-plus:
  configuration:
    #    在映射实体或者属性的时候，把下划线写法变成驼峰写法
    map-underscore-to-camel-case: true
    #启用mybatis的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #??
  global-config:
    db-config:
      id-type: auto

reggie:
  path: C:\Users\Administrator\Desktop\reggie\
